# Generated by Django 5.1.15 on 2026-03-18 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        ('precios', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('subtotal_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonif_cliente_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonif_cliente_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bonif_pago_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bonif_pago_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_neto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_105_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_105_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_21_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_21_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('confirmada', 'Confirmada')], default='borrador', max_length=10)),
                ('confirmada_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.formapago')),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='catalogo.implemento')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='precios.listaprecio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='CotizacionDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_acumulado', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensiones', to='cotizaciones.cotizacion')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.propiedad')),
            ],
            options={
                'verbose_name': 'Dimensión de Cotización',
                'verbose_name_plural': 'Dimensiones de Cotización',
                'db_table': 'cotizacion_dimensiones',
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('precio_linea', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.familia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Item de Cotización',
                'verbose_name_plural': 'Items de Cotización',
                'db_table': 'cotizacion_items',
            },
        ),
    ]
