# Generated by Django 5.1.15 on 2026-03-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='comision_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='comision_porcentaje_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
