# Generated by Django 5.1.15 on 2026-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_aprobada_at_cotizacion_aprobada_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('confirmada', 'Confirmada'), ('descartada', 'Descartada')], default='borrador', max_length=10),
        ),
    ]
