# Generated by Django 5.1.15 on 2026-03-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocliente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
