# Generated by Django 5.1.15 on 2026-03-18 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('bonif_max_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Bonificación máxima (%)')),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
            },
        ),
    ]
