# Generated by Django 5.1.15 on 2026-03-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='color_primario',
            field=models.CharField(default='#0f172a', max_length=7, verbose_name='Color primario (header PDF)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='color_secundario',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Color secundario (acentos PDF)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo'),
        ),
    ]
