# Generated by Django 5.1.15 on 2026-03-19 16:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_color_primario_tenant_color_secundario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='bonif_max_porcentaje',
        ),
        migrations.AddField(
            model_name='tenant',
            name='comision_impacto_bonif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), max_digits=3, verbose_name='Factor impacto bonificación sobre comisión'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mostrar_comisiones',
            field=models.BooleanField(default=False, verbose_name='Vendedor ve su comisión'),
        ),
    ]
