# Generated by Django 5.1.15 on 2026-03-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('accesorios_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de accesorios')),
                ('nivel_rodado', models.IntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Implemento',
                'verbose_name_plural': 'Implementos',
                'db_table': 'implementos',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.IntegerField()),
                ('tipo_seleccion', models.CharField(choices=[('O', 'Uno (radio)'), ('Y', 'Varios (checkbox)')], default='O', max_length=1)),
                ('obligatoria', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=2)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='catalogo.implemento')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familias',
                'ordering': ['implemento', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=300)),
                ('cod_comercio', models.CharField(blank=True, max_length=100, null=True)),
                ('plano', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=21, max_digits=5, verbose_name='IVA (%)')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.familia')),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogo.implemento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['familia', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Vetado', 'Vetado'), ('Forzado', 'Forzado')], max_length=7)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('producto_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_hijo', to='catalogo.producto')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilidades_padre', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Compatibilidad',
                'verbose_name_plural': 'Compatibilidades',
                'db_table': 'compatibilidades',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('agregacion', models.CharField(choices=[('SUM', 'Suma'), ('MAX', 'Máximo')], default='SUM', max_length=3)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'db_table': 'propiedades',
            },
        ),
        migrations.CreateModel(
            name='ProductoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Exacto', 'Exacto'), ('Minimo', 'Mínimo'), ('Maximo', 'Máximo')], default='Exacto', max_length=6)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_neto', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('prioridad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to='catalogo.producto')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_propiedades', to='catalogo.propiedad')),
            ],
            options={
                'verbose_name': 'Producto-Propiedad',
                'verbose_name_plural': 'Producto-Propiedades',
                'db_table': 'producto_propiedades',
            },
        ),
    ]
