# Generated by Django 5.1.15 on 2026-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link_web',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link web'),
        ),
    ]
