# Generated by Django 5.1.15 on 2026-03-18 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('historica', 'Histórica'), ('borrador', 'Borrador')], default='borrador', max_length=10)),
                ('ajuste_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ajuste (%)')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_creadas', to=settings.AUTH_USER_MODEL)),
                ('lista_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_derivadas', to='precios.listaprecio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'listas_precios',
            },
        ),
        migrations.CreateModel(
            name='Prearmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=300)),
                ('precio_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('implemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prearmados', to='catalogo.implemento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Prearmado',
                'verbose_name_plural': 'Prearmados',
                'db_table': 'prearmados',
            },
        ),
        migrations.CreateModel(
            name='EstructuraPrearmado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_prearmados', to='catalogo.producto')),
                ('prearmado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estructura', to='precios.prearmado')),
            ],
            options={
                'verbose_name': 'Estructura Prearmado',
                'verbose_name_plural': 'Estructura Prearmados',
                'db_table': 'estructura_prearmados',
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precios_editados', to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='precios.listaprecio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Precio de Producto',
                'verbose_name_plural': 'Precios de Productos',
                'db_table': 'precios_productos',
                'unique_together': {('lista', 'producto')},
            },
        ),
    ]
